### ISSUE TITLE
VS code for Mac

### ISSUE THREAD

**Issue by nbrandaleone** [OptimaSystems/vscode-apl-language-client#2]
Hello, I have downloaded the VS extensions, for my Mac.  While I can get the syntax highlighting working using the other APL extension, the full feature set of the language server is not working for me. I have set the executable path: "/Applications/Dyalog-17.0.app/Contents/MacOS/Dyalog-17.0".

Anything else?

**Comment by e9gille** [comment]
Hi Nick
At the moment you need to provide the path to the dyalog binary:
`/Applications/Dyalog-17.0.app/Contents/Resources/Dyalog/dyalog`
The extension defaults to launch `dyalog` so if you add an entry to your PATH it will also work. In `~/.bash_profile` add the following line:

`export PATH=$PATH:/Applications/Dyalog-17.0.app/Contents/Resources/Dyalog`

**Comment by nbrandaleone** [comment]
Thanks for the note. I will try it later today.
