### ISSUE TITLE
Support more file-extensions

### ISSUE THREAD

**Issue by mbaas2** [OptimaSystems/vscode-apl-language-client#3]
Would be nice if we could use client & server on .mipage and the new extensions from ACRE

**Comment by e9gille** [comment]
That is already the case. Are you saying it doesn't work for you? Can you give me an example?

**Comment by mbaas2** [comment]
So I was mislead a bit by the doc for the "APL Language"-extension - it made me believe it would also be useable standalone. After enabling the Client-Extension, too, I now see syntax-colouring in .mipage-files. However, I noticed other issues, too - which supported my assumption that -mipage wasn't supported. I'll create individual issues for these.

**Comment by e9gille** [comment]
>  it made me believe it would also be useable standalone

That is correct, the APL Language extension should be OK to use stand alone if all you want is syntax highlighting and the APL font. You only need the `APL Language Server Client` if you also want tooltip and prefix completion. I've just tested it again with the latter disabled (restarted VSCode as well to be sure) and it renders ".mipage" files as APL.
