### ISSUE TITLE
Tool tips in primitives not showing

### ISSUE THREAD

**Issue by mbaas2** [OptimaSystems/vscode-apl-language-client#4]
Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by e9gille** [comment]
Have you made sure to restart VSCode after enabling the extension?

**Comment by mbaas2** [comment]
Absolutely. Even several times ;)

**Comment by mbaas2** [comment]
Sorted :)
