### ISSUE TITLE
Prefix completition with <

### ISSUE THREAD

**Issue by mbaas2** [OptimaSystems/vscode-apl-language-client#5]
Backtick is a dead key on german kbd, so I got used to using `<` in RIDE and have tried setting `"apl.server.prefixCompleteCharacters": "`<"` - but this does not have an effect (I was expecting `<l` to give me `⎕`)

**Comment by e9gille** [comment]
Just tested this and it works, but it seems to take a couple of attempts before the change is picked up on the client side.

If you change the setting and then try it out in an APL file, the first time it doesn't seem to trigger the suggestions box at all. The second attempt it comes up but doesn't then do the substitution when you hit the `l` key. Third time's the charm!

However, if you subsequently restart VSCode it works straight away. So unless you are in the habit of changing the prefix key often, it won't cause you a problem. I'm not sure why the issue exists as it is a VSCode problem as far as I can tell.

Could you test again please?

**Comment by mbaas2** [comment]
I'll email you - we better sort this directly then...
